homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.login_view, name="login"),
    path('compose/', views.compose_view, name="compose"),
    path('inbox/', views.inbox_view, name="inbox"),
    path('sent/', views.sent_view, name="sent"),
    path('trash/', views.trash_view, name="trash"),
    path('options/', views.options_view, name="options"),
    path('logout/', views.login_view, name="login")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
    
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User

class UserDetails(models.Model):
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

class option(models.Model):
    option = models.CharField(max_length=100)

class Details:
    email : str
    password : str

class Compose:
    recipient : str
    subject : str
    body : str


class Mail(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_emails')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_emails')
    subject = models.CharField(max_length=255)
    body = models.TextField()
    date = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    tag = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=[('read', 'read'), ('unread', 'unread'), ('sent','sent')], default='unread')
    
    def __str__(self) -> str:
        return self.subject  

homepage/forms.py
from django import forms
from . import models

class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserDetails
        fields = ['email','password']
        widgets = {
        'email' : forms.EmailInput(),
        'password': forms.PasswordInput(),
        }

homepage/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Details
from .models import Compose
import imaplib,email
from gtts import gTTS
import os
from .models import Mail
from playsound import playsound
from django.http import HttpResponse
import speech_recognition as sr
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from django.http import JsonResponse
import re
import imaplib
import email
# login
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login




file = "good"
i=0
passwrd = ""
addr = ""
item =""
subject = ""
body = ""
s = smtplib.SMTP('smtp.gmail.com', 587)
#email_username = 'satyamtiwari4430@digipodium.com'
#email_password = 'projectforblind'
email_username = 'group91235@gmail.com'
email_password = 'rfqrbippjcypxzrg'

s.starttls()
s.login(email_username, email_password)
attachment_dir = 'C:/Users/HP/Desktop/voice_based_email/mysite/homepage/attachments'

def texttospeech(text, filename):
    filename = f'{filename}.mp3'
    flag = True
    while flag:
        try:
            tts = gTTS(text=text, lang='en', slow=False)
            tts.save(filename)
            flag = False
        except Exception as e:
            print('Trying again', e)
            os.remove(filename)
    if os.path.exists(filename):
        playsound(filename)
        os.remove(filename)
    else:
        print("The file does not exist")
    return

def speechtotext(duration):
    global i, addr, passwrd
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source, duration=1)
        #r.adjust_for_ambient_noise(source, duration=0.2)
        playsound('speak.mp3')
        #audio = r.listen(source, phrase_time_limit=duration)
        audio = r.listen(source, timeout=4)
        #audio = r.listen(source)
    try:
        response = r.recognize_google(audio,language="en-US")
        print("Res is ",response)
    except:
        
        response = 'N'
        print("Res is1 ",response)
    return response

def convert_special_char(text):
    temp=text
    special_chars = ['attherate','dot','underscore','dollar','hash','star','plus','minus','space','dash']
    for character in special_chars:
        while(True):
            pos=temp.find(character)
            if pos == -1:
                break
            else :
                if character == 'attherate':
                    temp=temp.replace('attherate','@')
                elif character == 'dot':
                    temp=temp.replace('dot','.')
                elif character == 'underscore':
                    temp=temp.replace('underscore','_')
                elif character == 'dollar':
                    temp=temp.replace('dollar','$')
                elif character == 'hash':
                    temp=temp.replace('hash','#')
                elif character == 'star':
                    temp=temp.replace('star','*')
                elif character == 'plus':
                    temp=temp.replace('plus','+')
                elif character == 'minus':
                    temp=temp.replace('minus','-')
                elif character == 'space':
                    temp = temp.replace('space', '')
                elif character == 'dash':
                    temp=temp.replace('dash','-')
                elif character==' ':
                    temp=temp.replace(' ','')
    return temp


def login_view(request):
    #if request.user.is_authenticated:
    #    return redirect('homepage:options')
    global i, addr, passwrd 
    print(i, addr, passwrd)
    if request.method == 'POST':
        text1 = "Welcome to our Voice Based Email. Login with your email account in order to continue. "
        texttospeech(text1, f'{file}{i}')
        i += 1
        
        flag = True
        while (flag):
            texttospeech("Enter your Email", f'{file}{i}')
            i += 1
            addr = speechtotext(10)
            #addr='group91235@gmail.com'
            if addr=='group 91235@gmail.com':
                addr='group91235@gmail.com'
            if addr != 'N':
                texttospeech("You meant " + addr + " say Continue to confirm or repeat to enter again", f'{file}{i}')
                i += 1
                say = speechtotext(3)
                #say='yes'
                print("Say is  ",say)
                #if say == 'yes' or say == 'Yes':
                say=say.lower()
                if say == 'continue':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", f'{file}{i}')
                i +=1
        addr = addr.strip()
        addr = addr.replace(' ', '')
        addr = addr.lower()
        addr = convert_special_char(addr)
        print(addr)
        request.email = addr

        flag = True
        while (flag):
            texttospeech("Enter your password", f'{file}{i}')
            i +=1
            passwrd = speechtotext(10)
            
            if addr != 'N':
                texttospeech("You meant " + passwrd + " say continue to confirm or repeat to enter again", f'{file}{i}')
                i +=1
                say = speechtotext(3)
                #say='yes'
                say=say.lower()
                if say == 'continue':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", f'{file}{i}')
                i +=1
        passwrd = passwrd.strip()
        passwrd = passwrd.replace(' ', '')
        passwrd = passwrd.lower()
        passwrd = convert_special_char(passwrd)
        print(passwrd)
        try:
            #user = User.objects.get(email=addr)
            #if user.check_password(passwrd):
            #    login(request, user)
            #if request.user.is_authenticated:
            print("Email ",addr)
            print("Password ",passwrd)
            if addr=='group91235@gmail.com' and passwrd=='12345':
                texttospeech("Congratulations. You have logged in successfully. You will now be redirected to the menu page.", f'{file}{i}')
                i +=1
                #return render(request,'homepage/options.html')
                return JsonResponse({'result' : 'success'})
            else:
                texttospeech("Invalid Login Details. Please try again.", f'{file}{i}')
                i +=1
                #return render(request,'homepage/login.html')
                return JsonResponse({'result': 'failure'})
        except:
            #texttospeech("exception"):
            #texttospeech("Invalid Login Details. Please try again.", f'{file}{i}')
            #i +=1
            #return JsonResponse({'result': 'failure'})
            texttospeech("Congratulations. You have logged in successfully. You will now be redirected to the menu page.", f'{file}{i}')
            i +=1
                #return render(request,'homepage/options.html')
            return JsonResponse({'result' : 'success'})
    
    detail  = Details()
    detail.email = addr
    detail.password = passwrd
    return render(request, 'homepage/login.html', {'detail' : detail}) 
def logout(request):
    print("Logout 1")
    return render(request, 'homepage/login.html') 
def options_view(request):
    global i, addr, passwrd
    if request.method == 'POST':
        flag = True
        texttospeech("You are logged into your account. What would you like to do ?", f'{file}{i}')
        i +=1
        while(flag):
            texttospeech("To compose an email say compose. To open Inbox folder say Inbox. To open drive folder say drive. To open Trash folder say Trash. To Logout say Logout. say continue to continue the process and repeat to repeat again?", f'{file}{i}')
            i +=1
            #playsound('speak.mp3')
            say = speechtotext(3)
            say=say.lower()
            if say == 'continue':
                flag = False
            #if say == 'No' or say == 'no':
            #    flag = False
        texttospeech("Enter your desired action", f'{file}{i}')
        i +=1
        act = speechtotext(5)
        act = act.lower()
        #act='sent'
        print('action is ', act)
        if act == 'compose':
            return JsonResponse({'result' : 'compose'})
        elif act == 'inbox':
            return JsonResponse({'result' : 'inbox'})
        elif act == 'drive':
            return JsonResponse({'result' : 'sent'})
        elif act == 'trash':
            return JsonResponse({'result' : 'trash'})
        elif act == 'log out' or act =='logout':
            addr = ""
            passwrd = ""
            texttospeech("You have been logged out of your account and now will be redirected back to the login page.",f'{file}{i}')
            i +=1
            return JsonResponse({'result': 'logout'})
        else:
            texttospeech("Invalid action. Please try again.", f'{file}{i}')
            i +=1
            return JsonResponse({'result': 'failure'})
    elif request.method == 'GET':
        return render(request, 'homepage/options.html')

def compose_view(request):
    global i, addr, passwrd, s, item, subject, body
    if request.method == 'POST':
        text1 = "You have reached the page where you can compose and send an email. "
        texttospeech(text1, f'{file}{i}')
        i +=1
        flag = True
        flag1 = True
        #fromaddr = "satyamtiwari.345@yahoo.com"
        fromaddr=email_username
        toaddr = list()
        while flag1:
            while flag:
                texttospeech("enter receiver's email address:", f'{file}{i}')
                i +=1
                to = ""
                to = speechtotext(15)
                if to != 'N':
                    

homepage/templates/homepage/inbox.html
{% extends 'base_layout.html' %}

{% block content %}

	<body onmousedown = "SendPostRequestInbox(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)">
			<div class="masthead-content">
				<div class="container" >
					<center>
						<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">INBOX PAGE</h4>			
						<br>
							<h2> What would you like to do? <h2><br>
					</center>
					
				<table align="center" >
					<tr>
						<td>s
							
								<input href="compose.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								class="button" role="button"
								style="width: 250px; background-color: black;" type="submit" 
								value="UNREAD"  style="background-color: black;">
						</td>
					</tr>
						
					<tr>
						<td>
							
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="SEARCH" >
						</td>

					</tr>
						
					<tr>
						<td>
							
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="RETURN">
						</td>
					</tr>
						
					
					<tr>
						<td>
							
								<input href="login.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT">
						</td>
					</tr>
						

				</table>
		
				</div>
			</div>
			<div class="bg-circle-1 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-2 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-3 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-4 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestInbox(event){
		$.ajax({
        url: "{% url 'homepage:inbox' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

homepage/templates/homepage/login - Copy.html
{% extends 'base_layout.html' %}

{% block content %}
    <body onmousedown = "SendPostRequestHome(event)" >
	
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-center text-white">
			<div class="masthead-content">
				<div class="container">
					<h1  style="margin-top:-60px; font-size:60px;color: black;" >LOGIN HERE</h1>
					
				<form action="homepage/login.html" method="POST">
					<br><br><br><br>
					<div class="container" >
						
						
						<div class="login" id = "here">
							<script> 
								$(document).ready(function(){
								setInterval(function(){
									  $("#here").load(window.location.href + " #here" );
								}, 1000);
								});
								</script>
							
							{% csrf_token %}
							  <h3 style="color: black;text-align: left;margin-left: 10%;">Email:</h3>
					
							<input type="text" placeholder="Email" name="email"required value={{detail.email}} >
					
							  <br><br>
							  <h3 style="color: black;text-align: left;margin-left: 10%;">Password: </h3>
							 <input type="password" placeholder="Password" name="password"required value={{detail.password}} >
					
							   <a href="options.html"> 
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" role="button" type="submit" value="LOGIN"style="background-color: black;"></a>
							  <br>
							  
							  
							</div>
						</div>							   
					</div>
				</div>
			</form>
				</div>
			</div>
			<div class="bg-circle-1 bg-circle"></div>
			<div class="bg-circle-2 bg-circle"></div>
			<div class="bg-circle-3 bg-circle"></div>
			<div class="bg-circle-4 bg-circle"></div>
		</header>

		<script>
		
			function SendPostRequestHome(event){
				
				$.ajax({
				url: "{% url 'homepage:login' %}",
				method: 'POST',
				data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
				success: function (data) {
					
					if(data.result == 'success'){
						
						// post to homepage:options
						window.location = "{% url 'homepage:options' %}";
					}
					else if(data.result == 'failure'){
						window.location = "{% url 'homepage:login' %}";
					}
				}
			});
			}
			</script>
			
			<footer class="py-5 bg-black">
				<div class="container">
					<p class="text-center text-white m-0 small"></p>
				</div>
			</footer>


{% endblock %}

homepage/templates/homepage/options.html
{% extends 'base_layout.html' %}

{% block content %}

	<body onmousedown = "SendPostRequestOptions(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)">
			<div class="masthead-content">
				<div class="container" >
					<center>
						<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 90px;color:black;">MENU PAGE</h4>			
						<br>
    
						<h2> What would you like to do? <h2><br>
						</center>
					
				<div container>
				<div class ="options">

				
				<table align="center" >
					<tr>
						<td>
							<a href="compose.html"> 
								<input href="compose.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								class="button" role="button"
								style="width: 250px; background-color: black;" type="submit" 
								value="COMPOSE"  style="background-color: black;"></a>
						</td>
					</tr>
						
					<tr>
						<td>
							<a href="inbox.html"> 
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="INBOX" ></a>
						</td>

					</tr>
						
					<tr>
						<td>
							<a href="sent.html"> 
								<input href="sent.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="DRIVE"></a>
						</td>
					</tr>
						
					<tr>
						<td>
							<a href="trash.html"> 
								<input href="trash.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button" 
								style="width: 250px; background-color: black;"  type="submit" 
								value="TRASH"></a>
						</td>
					</tr>
					<tr>
						<td>
							<a href="login.html"> 
								<input href="logout.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT"></a>
						</td>
					</tr>
						

				</table>
			</div>
		</div>
						
		</div>
			</div>
			<div class="bg-circle-1 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-2 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-3 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-4 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestOptions(event){
		$.ajax({
        url: "{% url 'homepage:options' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'compose'){
				window.location = "{% url 'homepage:compose' %}";
			}
			else if(data.result == 'sent'){
				window.location = "{% url 'homepage:sent' %}";
			}	
			else if(data.result == 'inbox'){
				window.location = "{% url 'homepage:inbox' %}";
			}
			else if(data.result == 'trash'){
				window.location = "{% url 'homepage:trash' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'homepage:options' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

homepage/templates/homepage/sent.html
{% extends 'base_layout.html' %}

{% block content %}
	<body onmousedown = "SendPostRequestSent(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)">
			<div class="masthead-content">
				<div class="container" >
					<center>
						<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">DRIVE MAILS PAGE</h4>			
						<br>
						<h2> What would you like to do? <h2><br>
						
					</center>
					

				
				<table align="center" >
					<tr>
						<td>
							
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="SEARCH" >
						</td>

					</tr>
						
					<tr>
						<td>
							
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="RETURN">
						</td>
					</tr>
						
					
					<tr>
						<td>
							
								<input href="login.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT">
						</td>
					</tr>
						

				</table>
			
				</div>
			</div>
			<div class="bg-circle-1 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-2 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-3 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-4 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestSent(event){
		$.ajax({
        url: "{% url 'homepage:sent' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

homepage/templates/homepage/trash.html
{% extends 'base_layout.html' %}

{% block content %}
	<body onmousedown = "SendPostRequestTrash(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)">
			<div class="masthead-content">
				<div class="container" >
				<center>
					<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">TRASH FOLDER</h4>			
						<br>
						<h2> What would you like to do? <h2><br>
					
				</center>
				
				<table align="center" >
				<tr>
						<td>
							
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="READ" >
						</td>

					</tr>
						
					<tr>
						<td>
							
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="RETURN">
						</td>
					</tr>
						
					
					<tr>
						<td>
							
								<input href="login.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT">
						</td>
					</tr>
						

				</table>
			
				</div>
			</div>
			<div class="bg-circle-1 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-2 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-3 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
			<div class="bg-circle-4 bg-circle" style="background-image: url(https://png.pngtree.com/thumb_back/fh260/background/20210915/pngtree-marble-texture-dark-blue-watercolor-smudge-background-image_883769.jpg)"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestTrash(event){
		$.ajax({
        url: "{% url 'homepage:trash' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}